/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/join/$token': typeof JoinTokenRoute
  '/pay/$token': typeof PayTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/join/$token': typeof JoinTokenRoute
  '/pay/$token': typeof PayTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/join/$token': typeof JoinTokenRoute
  '/pay/$token': typeof PayTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kebijakan-privasi'
    | '/syarat-ketentuan'
    | '/join/$token'
    | '/pay/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kebijakan-privasi'
    | '/syarat-ketentuan'
    | '/join/$token'
    | '/pay/$token'
  id:
    | '__root__'
    | '/'
    | '/kebijakan-privasi'
    | '/syarat-ketentuan'
    | '/join/$token'
    | '/pay/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  JoinTokenRoute: typeof JoinTokenRoute
  PayTokenRoute: typeof PayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  JoinTokenRoute: JoinTokenRoute,
  PayTokenRoute: PayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
